old_top = {
    'autostart': False, 'version': '0.8.6', 'model': '7200', 'ghostios': False,
    'ghostsize': None, 'jitsharing': False, 'sparsemem': False,
    'idlemax': None, 'idlesleep': None, 'oldidle': False, 'debug': 0,
    '127.0.0.1:7200': {'workingdir': '/tmp', 'udp': 10001, 'port': None,
                       'qemupath': None, 'qemuimgpath': None, 'console': None,
                       'aux': None,
                       '3660': {
                           'image': '/home/daniel/GNS3/Images/3660/c3660-jk9o3'
                                    's-mz.124-19.image',
                           'idlepc': '0x6056c1ec', 'sparsemem': True,
                           'chassis': '3660', 'model': None, 'console': None,
                           'aux': None, 'mac': None, 'image1': None,
                           'image2': None, 'ram': None, 'nvram': None,
                           'cnfg': None, 'confreg': None, 'exec_area': None,
                           'clock': None, 'npe': None, 'midplane': None,
                           'disk0': None, 'disk1': None, 'mmap': None,
                           'ghostios': None, 'ghostsize': None,
                           'jitsharing': None, 'autostart': None,
                           'configuration': None, 'idlemax': None,
                           'idlesleep': None, 'oldidle': None, 'rom': None,
                           'x': None, 'y': None, 'hx': None, 'hy': None,
                           'key': None, 'serial': None, 'initrd': None,
                           'kernel': None, 'kernel_cmdline': None,
                           'options': None, 'nics': None, 'netcard': None,
                           'kvm': None, 'usermod': None, 'monitor': None,
                           'guestcontrol_user': None,
                           'guestcontrol_password': None,
                           'first_nic_managed': None, 'headless_mode': None,
                           'console_support': None,
                           'console_telnet_server': None, 'symbol': None},
                       'ROUTER R1': {'model': '3660', 'console': 2103,
                                     'aux': 2503, 'cnfg': 'configs/R1.cfg',
                                     'f0/0': 'SW1 2', 'x': -20.0, 'y': -12.0,
                                     'z': '1.0', 'mac': None, 'image': None,
                                     'image1': None, 'image2': None,
                                     'ram': None, 'nvram': None,
                                     'confreg': None, 'idlepc': None,
                                     'exec_area': None, 'clock': None,
                                     'npe': None, 'midplane': None,
                                     'disk0': None, 'disk1': None,
                                     'mmap': None, 'ghostios': None,
                                     'ghostsize': None, 'jitsharing': None,
                                     'sparsemem': None, 'autostart': None,
                                     'configuration': None, 'idlemax': None,
                                     'idlesleep': None, 'oldidle': None,
                                     'rom': None, 'hx': None, 'hy': None,
                                     'key': None, 'serial': None,
                                     'initrd': None, 'kernel': None,
                                     'kernel_cmdline': None, 'options': None,
                                     'nics': None, 'netcard': None,
                                     'kvm': None, 'usermod': None,
                                     'monitor': None,
                                     'guestcontrol_user': None,
                                     'guestcontrol_password': None,
                                     'first_nic_managed': None,
                                     'headless_mode': None,
                                     'console_support': None,
                                     'console_telnet_server': None,
                                     'symbol': None}},
    'GNS3-DATA': {'configs': 'configs', 'port': None, 'workingdir': None,
                  'qemupath': None, 'qemuimgpath': None, 'console': None,
                  'aux': None, 'udp': None}}

devices = {'R1': {'aux': 2503, 'model': 'c3600', 'console': 2103,
                  'f0/0': 'SW1 2', 'node_id': 1, 'type': 'Router',
                  'cnfg': 'configs/R1.cfg', 'x': -20.0, 'y': -12.0,
                  'hv_id': 0, 'z': '1.0'}}

conf = {0: {'idlepc': '0x6056c1ec', 'model': 'c3600',
            'image': '/home/daniel/GNS3/Images/3660/c3660-jk9o3s-mz.124-19.'
                     'image', 'chassis': '3660', 'sparsemem': True}}
